kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: golang:1.12
  commands:
  - go build
  when:
    branch: [master]

---
kind: pipeline
type: docker
name: frontend

steps:
- name: build
  image: golang:1.12
  commands:
  - echo hello world
  when:
    branch: [dev]
