---
kind: pipeline
type: docker
name: deploy

steps:
- name: test
  image: docker
  environment:
    DRONE_SSH_PWD:
      from_secret: DRONE_SSH_PWD
    DRONE_SSH_KEY:
      from_secret: DRONE_SSH_KEY
  commands:
  - echo pwd $DRONE_SSH_PWD
  - echo key $DRONE_SSH_KEY
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: ssh_host
    username: root
    password:
      from_secret: ssh_pwd
    port: 22
    key:
      from_secret: ssh_key
    script:
      - docker ps