---
kind: pipeline
type: docker
name: test

steps:
- name: handler_test
  image: golang:1.12
  # volumes:
  #   - name: cache
  #     path: /tmp/cache
  # environment:
  #   GOPROXY: https://goproxy.cn
    # GO111MODULE: off
  commands:
  # - cp /tmp/cache/config.yml .
  - go test
  - echo hello world
  - go build
- name: build_dev
  image: golang:1.12
  depends_on:
  - handler_test
  commands:
  - go build
  - mv drone-demo /data
- name: build_test
  image: golang:1.12
  commands:
  - echo build test
  when:
    branch: [test]
- name: deploy
  image: docker
  depends_on:
  - build_dev
  commands:
  - cd /data
  - docker build -t drone-demo .

# ---
# kind: pipeline
# type: docker
# name: deploy

# steps:
# - name: deploy_dev
#   image: docker
#   depends_on:
#   - handler_test
#   commands:
#   - echo hello
# ---
# kind: pipeline
# type: docker
# name: deploy
# - name: deploy_dev
#   image: docker
#   depends_on:
#     - go_test
#   commands:
#     - echo hello
# # volumes:
# - name: cache
#   host:
#     path: /root/drone