---
kind: pipeline
type: docker
name: test

steps:
- name: handler_test
  image: golang:1.12
  # volumes:
  #   - name: cache
  #     path: /tmp/cache
  # environment:
  #   GOPROXY: https://goproxy.cn
    # GO111MODULE: off
  commands:
  # - cp /tmp/cache/config.yml .
  - go test
  - echo hello world
  - go build
- name: build_dev
  image: golang:1.12
  depends_on:
  - handler_test
  commands:
  - go build
  - mv drone-demo /data
- name: build_test
  image: golang:1.12
  commands:
  - echo build test
  when:
    branch: [test]
- name: deploy
  image: appleboy/drone-ssh
  depends_on:
  - build_dev
  settings:
    host: 
      from_secret: ssh_host
    username: root
    port: 22
    password:
      from_secret: ssh_pwd
    script_stop: true
    script:
      - cd drone
      - docker stop drone-demo
      - docker rm drone-demo
      - docker build -t drone-demo .
      # - lsof -i :20081 | grep -v PID |awk '{print $2}' | xargs kill -9
      # - nohup swagger serve --port 20081 --no-open  swagger.json &


# ---
# kind: pipeline
# type: docker
# name: deploy

# steps:
# - name: deploy_dev
#   image: docker
#   depends_on:
#   - handler_test
#   commands:
#   - echo hello
# ---
# kind: pipeline
# type: docker
# name: deploy
# - name: deploy_dev
#   image: docker
#   depends_on:
#     - go_test
#   commands:
#     - echo hello
# # volumes:
# - name: cache
#   host:
#     path: /root/drone