---
kind: pipeline
type: docker
name: test

steps:
- name: go_test
  image: golang:1.12
  # volumes:
  #   - name: cache
  #     path: /tmp/cache
  # environment:
  #   GOPROXY: https://goproxy.cn
    # GO111MODULE: off
  commands:
  # - cp /tmp/cache/config.yml .
  - go test
  - echo hello world
  - go build

---
kind: pipeline
type: docker
name: deploy
- name: deploy_dev
  image: docker
  depends_on:
    - go_test
  commands:
    - echo hello
# volumes:
# - name: cache
#   host:
#     path: /root/drone