---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: docker
  # volumes:
  #   - name: cache
  #     path: /tmp/cache
  # environment:
  #   GOPROXY: https://goproxy.cn
    # GO111MODULE: off
  commands:
  # - cp /tmp/cache/config.yml .
  - ls
  # - echo hello world
  - ls /data

# volumes:
# - name: cache
#   host:
#     path: /root/drone