---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: docker
  volumes:
    - name: config
      path: /tmp/cache
  # environment:
  #   GOPROXY: https://goproxy.cn
    # GO111MODULE: off
  commands:
  - echo hello
  - ls /tmp/cache/

volumes:
- name: config
  host:
    path: /root/volumes