---
kind: pipeline
type: docker
name: deploy

steps:
- name: ssh commands
  image: docker
  environment:
    DRONE_SSH_PWD:
      from_secret: DRONE_SSH_PWD
    DRONE_SSH_KEY:
      from_secret: DRONE_SSH_KEY
  commands:
  - echo pwd $DRONE_SSH_PWD
  - echo key $DRONE_SSH_KEY