---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: docker
  volumes:
    - name: cache
      path: /data
  # environment:
  #   GOPROXY: https://goproxy.cn
    # GO111MODULE: off
  privileged: true
  commands:
  - echo hello world
  - ls /data/

volumes:
- name: cache
  host:
    path: /root/drone